const routes = {
    home: '/',
    menu: '/menu',
    order: '/order',
    fogot: '/fogot',
    manage: '/manage',
    login: '/login',
    signup: '/signup',
    member: '/member',
    Table: '/Table',
    staff: '/staff',
    booking: '/booking',
    cart: '/cart',
    reset: '/reset',
    admin: '/admin',
    history: '/history',
    contact: '/contact',
    voucher: '/voucher',
    billist: '/bill',
    hitry: '/histry',
    detalbil: '/bill/:id',
    biifrom: '/bill/edit/:id',
};
export default routes;
